### ISSUE TITLE
Loadouts für Opfor

### ISSUE THREAD

**Issue by AdlerXiviD** [gruppe-adler/TvT_GTV.lythium#1]
Unterschiedliche Klassen für Opfor sollen Teamarbeit erzwingen:

- [x] Sapper mit Sprengsätzen (Sollen am besten nur gegen Fahrzeuge eingesetzt werden)
- [x] Recon (Drohne, Spottercam, Periskop)
- [x] Infiltrator
- [x] Digger
- [x] Heavy (Panzeraust 60)

**Comment by AdlerXiviD** [comment]
Recon evtl. ohne Spottercam, außer McDiod findet Lösung zwei Rucksäcke zu tragen.

**Comment by McDiod** [comment]
Lockpicks für statische Zivilfahrzeuge?
